bistecca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls','main'), namespace='main')),
]

main/urls.py
from django.urls import path, include
from .views import(
        index,
        login_view,
        logout_view,
        logout_after,
        registration_view,
        search_results,
        add_deal_adeguata,
        add_deal_anagrafica,
        registration_success,
        upload_files,
    )

urlpatterns = [
    path('index', index, name="index"),
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('logout_after', logout_after, name="logout-after"),
    path('register', registration_view, name="register"),
    path('search_results', search_results, name="search_results"),
    path('add_deal_adeguata', add_deal_adeguata, name="add_deal_adeguata"),
    path('add_deal_anagrafica', add_deal_anagrafica, name="add_deal_anagrafica"),
    path('registration_success', registration_success, name="registration_success"),
    path('upload_files', upload_files, name="upload_files"),
]

main/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserRole(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.role


class Deal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='nessuno')
    idcard_fronte = models.ImageField(verbose_name="Carta d'identita - Fronte", upload_to='images/idcards/fronte')
    idcard_retro = models.ImageField(verbose_name="Carta d'identita - Retro", upload_to='images/idcards/retro')
    ts_fronte = models.ImageField(verbose_name="Tessera Sanitatia - Fronte", upload_to='images/TS/fronte')
    ts_retro = models.ImageField(verbose_name="Tessera Sanitatia - Retro", upload_to='images/TS/retro')
    data_emissione = models.DateField(default=datetime.now())
    data_scadenza = models.DateField(default=datetime.now())
    numero_documento = models.CharField(max_length=20)
    comune_rilascio = models.CharField(max_length=100)

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Deal
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, HTML, Field, Row, Column, Submit
from django.urls import reverse_lazy

class DateInput(forms.DateInput):
    input_type = 'date'

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')
    role = forms.ChoiceField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('partner', 'Partner')])

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'role')

class AdeguataForm(forms.Form):
    idcard_fronte = forms.ImageField(label="Carta d'identita - Fronte")
    idcard_retro = forms.ImageField(label="Carta d'identita - Retro")
    ts_fronte = forms.ImageField(label="Tessera Sanitatia - Fronte")
    ts_retro = forms.ImageField(label="Tessera Sanitatia - Retro")
    data_emissione = forms.DateField(widget=DateInput)
    data_scadenza = forms.DateField(widget=DateInput)
    numero_documento = forms.CharField(max_length=20)
    comune_rilascio = forms.CharField(max_length=100)
    gdpr = forms.BooleanField(label='Dichiaro di aver preso visione dell\'informativa sulla privacy')

    class Meta:
        model = Deal
        fields = ('title', 'idcard_fronte','idcard_retro','ts_fronte','ts_retro','data_emissione', 
                  'data_scadenza', 'numero_documento', 'comune_rilascio')


class AnagraficaForm(forms.Form):
    nome_azienda = forms.CharField(max_length=100)
    data_costituzione = forms.DateField(widget=DateInput)
    p_iva = forms.CharField(max_length=11, min_length=11, label="Partita IVA")
    cf = forms.CharField(max_length=16, min_length=16, label="Codice Fiscale")
    
    sede_leg_citta = forms.CharField(max_length=50, label="Citt\u00E0")
    sede_leg_indirizzo = forms.CharField(max_length=50, label="Indirizzo")
    sede_leg_numero_civico = forms.CharField(max_length=50, label="Numero Civico")
    #sede_leg_cap = forms.CharField(max_length=50, label="CAP")


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse_lazy('add_deal_anagrafica')
        self.helper.form_method = 'GET'
    class Meta:
        model = Deal
        fields = ('nome_azienda', 'data_costituzione','p_iva','cf','sede_leg_citta', 
                  'sede_leg_indirizzo', 'sede_leg_numero_civico', 'sede_leg_cap')

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, auth
from .forms import RegistrationForm, AdeguataForm, AnagraficaForm
from .models import UserRole
from django.contrib import messages



# Create your views here.


def index(request):
    return render(request, 'index.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Login the user and redirect to the appropriate page
            user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                auth.login(request, user)
                return redirect('index')
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_after(request):
    auth.logout(request)
    return redirect('index')

def logout_view(request):
    return render(request, 'logout.html')

def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_role = UserRole.objects.create(user_id=user.id, role=request.POST['role'])
            user_role.save()

            # Redirect to success page
            return redirect('registration_success')
    else:
        form = RegistrationForm()
    context = {'form': form}
    return render(request, 'registration.html', context)

def add_deal_adeguata(request):
    form = AdeguataForm()
    context = {'form': form}
    return render(request, 'add_deal/add_deal_adeguata.html', context)

def add_deal_anagrafica(request):
    form = AnagraficaForm()
    context = {'form': form}
    return render(request, 'add_deal/add_deal_anagrafica.html', context)

def registration_success(request):
    return render(request, 'registration_success.html')

def upload_files(request):
    return render(request, 'upload_files.html')


def search_results(request):
    messages.info('CIAO CIAO')
    return render(request, 'search_results.html')

templates/add_deal/add_deal_adeguata.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content%}
<br />
<h1>Adeguata Verifica</h1>
<br />


<form action="upload_files" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <a href="{% static 'privacy.pdf' %}" target="_blank">Informativa sulla privacy</a>
    <button type="submit">Submit</button>
</form>

{% endblock %}

{% block extra_js %}
{{ form.media }}
{% endblock %}

templates/add_deal/add_deal_anagrafica.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content%}
<br />
<h1>Anagrafica</h1>
<br />
<h2>Azienda</h2>


<form action="add_deal_adeguata" >
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Submit</button>
</form>
<hr />

<br />
<h2>Legale Rappresentante</h2>

<hr />
<br />
<h2>Titolari Effettivi</h2>

{% endblock %}

{% block extra_js %}
{{ form.media }}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Softloans{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--<script src="{% static 'js/main.js'% }" defer></script>-->

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

    <link rel="icon" type="image.png" href="{% static 'favicon.ico' %}" />

    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">Softloans</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">Guida Rapida</a></li>
                    <li><a href="#">Altro</a></li>
                    <li><a href="#">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% block navbar %}
                    {% endblock %}
                    {% if user.is_authenticated %}
                        {% if user_role == 'seller' %}
                            {% include 'navbar_templates/seller_navbar.html' %}
                        {% elif user_role == 'buyer' %}
                            {% include 'navbar_templates/buyer_navbar.html' %}
                        {% elif user_role == 'partner' %}
                            {% include 'navbar_templates/partner_navbar.html' %}
                        {% endif %}
                        <li><a href="#">My Account</a></li>
                        <li><a href="{% url 'main:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'register' %}">Registrati</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% if user.is_authenticated %}
<h1>Welcome, {{user_name}}!</h1>
<h2>Role: {{user_role}}</h2>
{% else %}
<h1>Welcome to Softloans!</h1>
{% endif %}
<p>Ez loans belli belli</p>

<form action="{% url 'main:search_results' %}" method="get">
    <input type="text" name="location" placeholder="Cerca un annuncio...">
    <input type="date" name="checkin" placeholder="Cerca da questa data in poi">
    <input type="number" name="guests" placeholder="Min">
    <input type="number" name="guests" placeholder="Max">
    <button type="submit">Search</button>
</form>
<br />
<br />


<div class="deals-container">
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 1">
        <h3>Scialo lo Sukkia</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 2">
        <h3>Annuncio 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 3">
        <h3>Annuncio 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 4">
        <h3>Annuncio 4</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 5">
        <h3>Annuncio 5</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <div class="deal">
        <img src="{% static '/images/bistecca.jpg' %}" alt="Deal 6">
        <h3>Annuncio 6</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <a href="#">Visualizza</a>
    </div>
    <!-- Add more deal items here -->
</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>Login</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<h2>Logout</h2>
<form action="{% url 'main:logout_after' %}" method="post">
    {% csrf_token %}
    <p>Are you sure you want to log out?</p>
    <button type="submit">Logout</button>
    <a href="{% url 'index' %}">Cancel</a>
</form>
{% endblock %}

templates/navbar_templates/buyer_navbar.html
<li><a href="/cart/">Cart</a></li>

templates/navbar_templates/partner_navbar.html
<li><a href="#">Link per partner</a></li>

templates/navbar_templates/seller_navbar.html
<li><a href="/add_deal_anagrafica">Add Deal</a></li>           

templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>Register</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
{% endblock %}

templates/registration_success.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Registrazione avvenuta!</h1>
<a href="login">Vai al Login</a>

{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>Search Results</h1>
  {% if deals %}
<ul>
    {% for deal in deals %}
    <li>
        <h2>{{ deal.name }}</h2>
        <p>{{ deal.description }}</p>
        <p>Price per night: {{ deal.price }}</p>
        <a href="{% url 'deal_detail' deal.id %}">View Details</a>
    </li>
    {% endfor %}
</ul>
  {% else %}
<p>No deals found.</p>
  {% endif %}
{% endblock %}

templates/upload_files.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Deal uploaded! :)</h1>

{% endblock %}